M48
; DRILL file {KiCad 8.0.5} date 2024-10-10T02:04:09+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-10T02:04:09+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0925
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1122
%
G90
G05
T1
X6.4173Y-3.8524
X6.4173Y-4.1673
T2
X6.3386Y-3.3425
T3
X6.0453Y-3.3425
T4
X4.1984Y-4.303
X4.789Y-4.303
T5
X4.1984Y-4.4604
X4.789Y-4.4604
M30
