M48
; DRILL file {KiCad 8.0.8} date 2025-06-25T00:18:44+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-25T00:18:44+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0512
%
G90
G05
T1
X6.4173Y-3.8524
X6.4173Y-4.1673
T2
X6.3386Y-3.3425
T3
X6.0453Y-3.3425
M30
