name: Build PCB

on:
  push:
    branches:
      - '**'
    paths:
      - 'device/hardware/**'
  workflow_call:
  workflow_dispatch:
  
jobs:
  build-pcb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo add-apt-repository ppa:kicad/kicad-8.0-releases
          sudo apt-get update
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: kicad imagemagick
          version: 1.0

      - name: Test schematic ERC and PCB DRC
        run: |
          cd device/hardware
          kicad-cli sch erc -o fsk-energymeter-erc.rpt --severity-error --severity-warning --exit-code-violations fsk-energymeter.kicad_sch
          # skip DRC due to symbol library error. will be fixed in the future
          # kicad-cli pcb drc -o fsk-energymeter-drc.rpt --schematic-parity --severity-error --severity-warning --exit-code-violations fsk-energymeter.kicad_pcb

      - if: ${{ failure() }}
        run: |
          echo "##### ERC REPORT #####"
          cat device/hardware/fsk-energymeter-erc.rpt
          echo "##### DRC REPORT #####"
          cat device/hardware/fsk-energymeter-drc.rpt

      - name: Build PCB schematic, artwork and 3d models
        run: |
          npm i -g svgexport
          mkdir -p kicad
          kicad-cli sch export svg device/hardware/fsk-energymeter.kicad_sch -o kicad --exclude-drawing-sheet --no-background-color
          kicad-cli pcb export svg device/hardware/fsk-energymeter.kicad_pcb -o kicad/fsk-energymeter-artwork.svg --layers "B.Cu,F.Cu,F.Silkscreen,B.Silkscreen,User.Drawings,Edge.Cuts" --exclude-drawing-sheet
          svgexport kicad/fsk-energymeter.svg kicad/fsk-energymeter-schematic-transparent.png 8000:
          convert kicad/fsk-energymeter-schematic-transparent.png -trim -bordercolor transparent -border 100x100 kicad/fsk-energymeter-schematic-transparent.png
          svgexport kicad/fsk-energymeter.svg kicad/fsk-energymeter-schematic.png 8000: "svg{background:white;}"
          convert kicad/fsk-energymeter-schematic.png -trim -bordercolor white -border 100x100 kicad/fsk-energymeter-schematic.png
          mv kicad/fsk-energymeter.svg fsk-energymeter-schematic.svg
          svgexport kicad/fsk-energymeter-artwork.svg kicad/fsk-energymeter-artwork-transparent.png 8000:
          convert kicad/fsk-energymeter-artwork-transparent.png -trim -bordercolor transparent -border 100x100 kicad/fsk-energymeter-artwork-transparent.png
          svgexport kicad/fsk-energymeter-artwork.svg kicad/fsk-energymeter-artwork.png 8000: "svg{background:#001023;}"
          convert kicad/fsk-energymeter-artwork.png -trim -bordercolor "#001023" -border 100x100 kicad/fsk-energymeter-artwork.png
          kicad-cli pcb export step -o kicad/fsk-energymeter-3d.stp --include-tracks device/hardware/fsk-energymeter.kicad_pcb
          kicad-cli pcb export vrml -o kicad/fsk-energymeter-3d.wrl device/hardware/fsk-energymeter.kicad_pcb
          cp -r device/hardware/jlcpcb/production_files kicad/gerbers

      - uses: actions/upload-artifact@v4
        with:
          name: fsk-energymeter-pcb
          path: kicad
